version: '3.8'

services:
  db:
    image: postgres:16
    container_name: my-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rgr
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: my-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: rgr
      DB_PORT: 5432
      PORT: 3000
    volumes:
      - backend_storage:/usr/src/app/storage
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: my-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://IP_адрес_сервера:3000

volumes:
  db_data:
  backend_storage: